== {POST} /MapConfigurations/{id}/Attachments/{ATTACHMENT_ID} - Replace an existing attachment for a Map Configuration

Executing a PUT at the MapConfiguration/{config_id}/Attachments endpoint with a formdata multipart file containing the desired attachment binary will replace the existing attachment document for this configuration.

Example of curl command:

[source,bash]
----
$ curl -v -F key1=value1 -F upload=@localfilename 'http://localhost:8080/MapConfigurations/my-application/Attachments/my-attachment' -i -X POST\
    -H 'Accept: application/json'
----

Example of HTTPie command:

[source,bash]
----
$ http POST'http://localhost:8080/MapConfigurations/my-application/Attachments/my-attachment' \
    'file@attachment.json' \
    'Accept:application/json'
----

Path Parameters:

./MapConfigurations/{config_id}/Attachments/
|===
|Parameter|Description

|`config_id`
|The SMK Map Configuration ID

|===

Request Parameters:

./MapConfigurations/{config_id}/Attachments/{attachment_id}/file=val
|===
|Parameter|Description

|file
|A multipart formdata object containing the file information (kml, zip, image, etc.)

|===

Example of http request:

[source,http,options="nowrap"]
----
POST /MapConfigurations/my-application/Attachments/my-attachment HTTP/1.1
(--- file stream not shown ---)
Accept: application/json
Host: localhost:8080

----

Example of http response:

[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=ISO-8859-1
Content-Length: 22

{ status: "Success!" }
----

Response body:

[source,options="nowrap"]
----
{ status: "Success!" }
----