== {DELETE} /MapConfiguration/{id}/Attachments/{attachment_id} - Delete an Attachment for a Map Configuration

Executing a DELETE at the /MapConfiguration/{id}/Attachments/{attachment_id} endpoint will attempt to delete the attachment. Ensure you have updated any links in layer configurations to this attachment, if necessary.

NOTE: Deleting a layer with attached vector information will automatically trigger an attachment delete.

Example of curl command:

[source,bash]
----
$ curl 'http://localhost:8080/MapConfigurations/my-application/Attachments/my-attachment' -i -X DELETE \
    -H 'Accept: application/json'
----

Example of HTTPie command:

[source,bash]
----
$ http DELETE 'http://localhost:8080/MapConfigurations/my-application/Attachments/my-attachment' \
    'Accept:application/json'
----

Path Parameters:

./MapConfigurations/{config_id}/Attachments/{attachment_id}
|===
|Parameter|Description

|`config_id`
|The SMK Map Configuration ID

|`attachment_id`
|The attachment ID for a map configurations attachment

|===

Example of http request:

[source,http,options="nowrap"]
----
DELETE /MapConfigurations/my-application/Attachments/my-attachment HTTP/1.1
Accept: application/json
Host: localhost:8080

----

Example of http response:

[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=ISO-8859-1
Content-Length: 22

{ status: "Success!" }
----

Response body:

[source,options="nowrap"]
----
{ status: "Success!" }
----